spring:
  profiles:
    active: cloud
  application:
    name: Configuration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MunSunch/SpringCloudConfig.git
          clone-on-start: true
          default-label: cloud
          search-paths:
            - 'config/{application}/{profile}'

management:
  endpoints:
    web:
      exposure:
        include: refresh

server:
  port: 8888