spring:
  profiles:
    active: native
  application:
    name: Configuration
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/Desktop/Project2/Configuration/config/{application}/{profile}

server:
  port: 8888